name: Deploy to Web Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: src/package-lock.json
      - name: Install dependencies
        working-directory: ./src
        run: npm ci
      - name: Build
        working-directory: ./src
        run: npm run build
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USER_NAME }}
          key: ${{ secrets.WEB_SERVER_PRIVATE_KEY }}
          script: |
            cd /var/www/slot-data-analysis/src/
            git pull
            php artisan migrate --force
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USER_NAME }}
          key: ${{ secrets.WEB_SERVER_PRIVATE_KEY }}
          source: /src/public/build/
          target: /var/www/slot-data-analysis/src/public/build/
